# Generated by Django 3.2.4 on 2021-08-24 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Electrodomestico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=35)),
                ('Activo', models.BooleanField(default=True)),
                ('Linea', models.CharField(max_length=1)),
            ],
        ),
    ]
