# Generated by Django 3.2.4 on 2021-08-24 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_alter_electrodomestico_linea'),
    ]

    operations = [
        migrations.AddField(
            model_name='electrodomestico',
            name='Consumo',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
