# Generated by Django 3.2.4 on 2021-08-24 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0004_ajustes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ajustes',
            new_name='Ajuste',
        ),
    ]
