# Generated by Django 3.2.4 on 2021-08-24 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0005_rename_ajustes_ajuste'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ajuste',
            name='Consumo',
        ),
    ]
