# Generated by Django 3.2.4 on 2021-08-24 13:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0006_remove_ajuste_consumo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FyHinicio', models.DateField()),
                ('FyHfin', models.DateField()),
                ('Tension', models.FloatField()),
                ('Corriente', models.FloatField()),
                ('FactorPotencia', models.FloatField()),
                ('Linea', models.PositiveIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='ajuste',
            name='NomLinea1',
            field=models.CharField(default=1, max_length=35),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ajuste',
            name='NomLinea2',
            field=models.CharField(default=1, max_length=35),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ajuste',
            name='NomLinea3',
            field=models.CharField(default=1, max_length=35),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='electrodomestico',
            name='Horas',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='electrodomestico',
            name='Marca',
            field=models.CharField(default=1, max_length=35),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='electrodomestico',
            name='Modelo',
            field=models.CharField(default=django.utils.timezone.now, max_length=35),
            preserve_default=False,
        ),
    ]
