# Generated by Django 3.2.7 on 2021-09-11 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0008_auto_20210906_1353'),
    ]

    operations = [
        migrations.CreateModel(
            name='Linea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=35)),
            ],
        ),
        migrations.DeleteModel(
            name='Lampara',
        ),
        migrations.RemoveField(
            model_name='ajuste',
            name='NomLinea1',
        ),
        migrations.RemoveField(
            model_name='ajuste',
            name='NomLinea2',
        ),
        migrations.RemoveField(
            model_name='ajuste',
            name='NomLinea3',
        ),
        migrations.AlterField(
            model_name='electrodomestico',
            name='Linea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sistema.linea'),
        ),
    ]
