# Generated by Django 3.2.4 on 2021-09-13 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0009_auto_20210911_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='electrodomestico',
            name='TipoClima',
            field=models.CharField(blank=True, choices=[('F', 'Frio'), ('C', 'Calor'), ('M', 'Mixto')], max_length=1),
        ),
        migrations.AlterField(
            model_name='electrodomestico',
            name='Marca',
            field=models.CharField(blank=True, max_length=35),
        ),
        migrations.AlterField(
            model_name='electrodomestico',
            name='Modelo',
            field=models.CharField(blank=True, max_length=35),
        ),
    ]
