# Generated by Django 3.2.4 on 2021-09-28 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0010_auto_20210913_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoraLuz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mes', models.CharField(max_length=35)),
                ('Amanecer', models.TimeField()),
                ('PuestaSol', models.TimeField()),
            ],
        ),
    ]
