# Generated by Django 3.2.4 on 2021-09-29 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0012_alter_horaluz_mes'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoraCasa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dia', models.PositiveIntegerField()),
                ('Inicio', models.TimeField()),
                ('Fin', models.TimeField()),
            ],
        ),
    ]
