# Generated by Django 3.2.4 on 2021-09-29 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0013_horacasa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horacasa',
            name='Dia',
            field=models.CharField(choices=[('1', 'Lunes'), ('2', 'Martes'), ('3', 'Miercoles'), ('4', 'Jueves'), ('5', 'Viernes'), ('6', 'Sabado'), ('7', 'Domingo')], max_length=1),
        ),
    ]
